version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Display received parameters
          command: |
            echo "Username: $CIRCLE_USERNAME"
            echo "Time in game: $CIRCLE_TIME_IN_GAME"
            echo "Message: $CIRCLE_MESSAGE"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
